version: 1.4.1-SNAPSHOT.{build}

#build C# solution and scala project
build_script:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: Build.cmd

# scripts to run after tests
after_test:
#  - cmd: Runsamples.cmd --validate
  - cmd: dir csharp\Microsoft.SparkCLR.1.0.0.nupkg

deploy:
  provider: NuGet
  # server:                  # remove to push to NuGet.org
  api_key:
    secure: 8/aUEkMI5hEiCETWDwHnRk7VXF5bPVMjrtGqYhLmDt/1A2uy8N8UwioZENNGGmdm
  skip_symbols: true
  # symbol_server:           # remove to push symbols to SymbolSource.org
  # artifact: /.*\.nupkg/
  artifact: csharp\Microsoft.SparkCLR.1.0.0.nupkg
